// flow-typed signature: dafab0f9d10a17202acaf4e0c5a1b4f0
// flow-typed version: <<STUB>>/actions-on-google_v^1.0.8/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'actions-on-google'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'actions-on-google' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'actions-on-google/actions-on-google' {
  declare module.exports: any;
}

declare module 'actions-on-google/actions-sdk-assistant' {
  declare module.exports: any;
}

declare module 'actions-on-google/api-ai-assistant' {
  declare module.exports: any;
}

declare module 'actions-on-google/assistant' {
  declare module.exports: any;
}

declare module 'actions-on-google/test/actions-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'actions-on-google/actions-on-google.js' {
  declare module.exports: $Exports<'actions-on-google/actions-on-google'>;
}
declare module 'actions-on-google/actions-sdk-assistant.js' {
  declare module.exports: $Exports<'actions-on-google/actions-sdk-assistant'>;
}
declare module 'actions-on-google/api-ai-assistant.js' {
  declare module.exports: $Exports<'actions-on-google/api-ai-assistant'>;
}
declare module 'actions-on-google/assistant.js' {
  declare module.exports: $Exports<'actions-on-google/assistant'>;
}
declare module 'actions-on-google/test/actions-test.js' {
  declare module.exports: $Exports<'actions-on-google/test/actions-test'>;
}
