// flow-typed signature: 5926d1b8968ebc0bedcc83b106cb9aaf
// flow-typed version: <<STUB>>/bluetooth-serial-port_v^2.1.2/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bluetooth-serial-port'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bluetooth-serial-port' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bluetooth-serial-port/examples/async' {
  declare module.exports: any;
}

declare module 'bluetooth-serial-port/examples/sync' {
  declare module.exports: any;
}

declare module 'bluetooth-serial-port/lib/bluetooth-serial-port' {
  declare module.exports: any;
}

declare module 'bluetooth-serial-port/lib/device-inquiry' {
  declare module.exports: any;
}

declare module 'bluetooth-serial-port/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bluetooth-serial-port/examples/async.js' {
  declare module.exports: $Exports<'bluetooth-serial-port/examples/async'>;
}
declare module 'bluetooth-serial-port/examples/sync.js' {
  declare module.exports: $Exports<'bluetooth-serial-port/examples/sync'>;
}
declare module 'bluetooth-serial-port/lib/bluetooth-serial-port.js' {
  declare module.exports: $Exports<'bluetooth-serial-port/lib/bluetooth-serial-port'>;
}
declare module 'bluetooth-serial-port/lib/device-inquiry.js' {
  declare module.exports: $Exports<'bluetooth-serial-port/lib/device-inquiry'>;
}
declare module 'bluetooth-serial-port/test/index.js' {
  declare module.exports: $Exports<'bluetooth-serial-port/test/index'>;
}
