// flow-typed signature: 7168249a2a7aea08310aeb7b4372eb2f
// flow-typed version: <<STUB>>/firebase_v^1.1.3/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase/lib/firebase-node' {
  declare module.exports: any;
}

declare module 'firebase/lib/firebase-web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase/lib/firebase-node.js' {
  declare module.exports: $Exports<'firebase/lib/firebase-node'>;
}
declare module 'firebase/lib/firebase-web.js' {
  declare module.exports: $Exports<'firebase/lib/firebase-web'>;
}
