// flow-typed signature: 3662b5f66b381682fbe41b1a37b0e885
// flow-typed version: <<STUB>>/flickr-sdk_v^2.0.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flickr-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'flickr-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flickr-sdk/build/flickr-sdk' {
  declare module.exports: any;
}

declare module 'flickr-sdk/build/flickr-sdk.min' {
  declare module.exports: any;
}

declare module 'flickr-sdk/build/flickr' {
  declare module.exports: any;
}

declare module 'flickr-sdk/build/flickr.min' {
  declare module.exports: any;
}

declare module 'flickr-sdk/example/node' {
  declare module.exports: any;
}

declare module 'flickr-sdk/flickr-sdk' {
  declare module.exports: any;
}

declare module 'flickr-sdk/gulpfile' {
  declare module.exports: any;
}

declare module 'flickr-sdk/lib/find-definition' {
  declare module.exports: any;
}

declare module 'flickr-sdk/lib/flickr-transport' {
  declare module.exports: any;
}

declare module 'flickr-sdk/lib/generate-url' {
  declare module.exports: any;
}

declare module 'flickr-sdk/lib/headers' {
  declare module.exports: any;
}

declare module 'flickr-sdk/lib/request-lite' {
  declare module.exports: any;
}

declare module 'flickr-sdk/lib/retryerrors' {
  declare module.exports: any;
}

declare module 'flickr-sdk/lib/sdk/albums' {
  declare module.exports: any;
}

declare module 'flickr-sdk/lib/sdk/auth' {
  declare module.exports: any;
}

declare module 'flickr-sdk/lib/sdk/galleries' {
  declare module.exports: any;
}

declare module 'flickr-sdk/lib/sdk/groups' {
  declare module.exports: any;
}

declare module 'flickr-sdk/lib/sdk/media' {
  declare module.exports: any;
}

declare module 'flickr-sdk/lib/sdk/people' {
  declare module.exports: any;
}

declare module 'flickr-sdk/lib/sdk/validate' {
  declare module.exports: any;
}

declare module 'flickr-sdk/lib/validate' {
  declare module.exports: any;
}

declare module 'flickr-sdk/shims/crypto-client' {
  declare module.exports: any;
}

declare module 'flickr-sdk/shims/crypto-server' {
  declare module.exports: any;
}

declare module 'flickr-sdk/tasks/paths' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/albums' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/auth' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/config' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/context' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/fixtures/group-2786742@N24' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/fixtures/photo-21300619575' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/fixtures/reply-72157657157975579' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/flickr-sdk' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/flickr-transport' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/galleries' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/generate-url' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/groups' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/media' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/people' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/search' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/setup' {
  declare module.exports: any;
}

declare module 'flickr-sdk/test/validate' {
  declare module.exports: any;
}

declare module 'flickr-sdk/vendor/jssha' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flickr-sdk/build/flickr-sdk.js' {
  declare module.exports: $Exports<'flickr-sdk/build/flickr-sdk'>;
}
declare module 'flickr-sdk/build/flickr-sdk.min.js' {
  declare module.exports: $Exports<'flickr-sdk/build/flickr-sdk.min'>;
}
declare module 'flickr-sdk/build/flickr.js' {
  declare module.exports: $Exports<'flickr-sdk/build/flickr'>;
}
declare module 'flickr-sdk/build/flickr.min.js' {
  declare module.exports: $Exports<'flickr-sdk/build/flickr.min'>;
}
declare module 'flickr-sdk/example/node.js' {
  declare module.exports: $Exports<'flickr-sdk/example/node'>;
}
declare module 'flickr-sdk/flickr-sdk.js' {
  declare module.exports: $Exports<'flickr-sdk/flickr-sdk'>;
}
declare module 'flickr-sdk/gulpfile.js' {
  declare module.exports: $Exports<'flickr-sdk/gulpfile'>;
}
declare module 'flickr-sdk/lib/find-definition.js' {
  declare module.exports: $Exports<'flickr-sdk/lib/find-definition'>;
}
declare module 'flickr-sdk/lib/flickr-transport.js' {
  declare module.exports: $Exports<'flickr-sdk/lib/flickr-transport'>;
}
declare module 'flickr-sdk/lib/generate-url.js' {
  declare module.exports: $Exports<'flickr-sdk/lib/generate-url'>;
}
declare module 'flickr-sdk/lib/headers.js' {
  declare module.exports: $Exports<'flickr-sdk/lib/headers'>;
}
declare module 'flickr-sdk/lib/request-lite.js' {
  declare module.exports: $Exports<'flickr-sdk/lib/request-lite'>;
}
declare module 'flickr-sdk/lib/retryerrors.js' {
  declare module.exports: $Exports<'flickr-sdk/lib/retryerrors'>;
}
declare module 'flickr-sdk/lib/sdk/albums.js' {
  declare module.exports: $Exports<'flickr-sdk/lib/sdk/albums'>;
}
declare module 'flickr-sdk/lib/sdk/auth.js' {
  declare module.exports: $Exports<'flickr-sdk/lib/sdk/auth'>;
}
declare module 'flickr-sdk/lib/sdk/galleries.js' {
  declare module.exports: $Exports<'flickr-sdk/lib/sdk/galleries'>;
}
declare module 'flickr-sdk/lib/sdk/groups.js' {
  declare module.exports: $Exports<'flickr-sdk/lib/sdk/groups'>;
}
declare module 'flickr-sdk/lib/sdk/media.js' {
  declare module.exports: $Exports<'flickr-sdk/lib/sdk/media'>;
}
declare module 'flickr-sdk/lib/sdk/people.js' {
  declare module.exports: $Exports<'flickr-sdk/lib/sdk/people'>;
}
declare module 'flickr-sdk/lib/sdk/validate.js' {
  declare module.exports: $Exports<'flickr-sdk/lib/sdk/validate'>;
}
declare module 'flickr-sdk/lib/validate.js' {
  declare module.exports: $Exports<'flickr-sdk/lib/validate'>;
}
declare module 'flickr-sdk/shims/crypto-client.js' {
  declare module.exports: $Exports<'flickr-sdk/shims/crypto-client'>;
}
declare module 'flickr-sdk/shims/crypto-server.js' {
  declare module.exports: $Exports<'flickr-sdk/shims/crypto-server'>;
}
declare module 'flickr-sdk/tasks/paths.js' {
  declare module.exports: $Exports<'flickr-sdk/tasks/paths'>;
}
declare module 'flickr-sdk/test/albums.js' {
  declare module.exports: $Exports<'flickr-sdk/test/albums'>;
}
declare module 'flickr-sdk/test/auth.js' {
  declare module.exports: $Exports<'flickr-sdk/test/auth'>;
}
declare module 'flickr-sdk/test/config.js' {
  declare module.exports: $Exports<'flickr-sdk/test/config'>;
}
declare module 'flickr-sdk/test/context.js' {
  declare module.exports: $Exports<'flickr-sdk/test/context'>;
}
declare module 'flickr-sdk/test/fixtures/group-2786742@N24.js' {
  declare module.exports: $Exports<'flickr-sdk/test/fixtures/group-2786742@N24'>;
}
declare module 'flickr-sdk/test/fixtures/photo-21300619575.js' {
  declare module.exports: $Exports<'flickr-sdk/test/fixtures/photo-21300619575'>;
}
declare module 'flickr-sdk/test/fixtures/reply-72157657157975579.js' {
  declare module.exports: $Exports<'flickr-sdk/test/fixtures/reply-72157657157975579'>;
}
declare module 'flickr-sdk/test/flickr-sdk.js' {
  declare module.exports: $Exports<'flickr-sdk/test/flickr-sdk'>;
}
declare module 'flickr-sdk/test/flickr-transport.js' {
  declare module.exports: $Exports<'flickr-sdk/test/flickr-transport'>;
}
declare module 'flickr-sdk/test/galleries.js' {
  declare module.exports: $Exports<'flickr-sdk/test/galleries'>;
}
declare module 'flickr-sdk/test/generate-url.js' {
  declare module.exports: $Exports<'flickr-sdk/test/generate-url'>;
}
declare module 'flickr-sdk/test/groups.js' {
  declare module.exports: $Exports<'flickr-sdk/test/groups'>;
}
declare module 'flickr-sdk/test/media.js' {
  declare module.exports: $Exports<'flickr-sdk/test/media'>;
}
declare module 'flickr-sdk/test/people.js' {
  declare module.exports: $Exports<'flickr-sdk/test/people'>;
}
declare module 'flickr-sdk/test/search.js' {
  declare module.exports: $Exports<'flickr-sdk/test/search'>;
}
declare module 'flickr-sdk/test/setup.js' {
  declare module.exports: $Exports<'flickr-sdk/test/setup'>;
}
declare module 'flickr-sdk/test/validate.js' {
  declare module.exports: $Exports<'flickr-sdk/test/validate'>;
}
declare module 'flickr-sdk/vendor/jssha.js' {
  declare module.exports: $Exports<'flickr-sdk/vendor/jssha'>;
}
