// flow-typed signature: a74203142eb9823e6dbe1a60b933a92f
// flow-typed version: <<STUB>>/noble_v^1.8.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'noble'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'noble' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'noble/examples/advertisement-discovery' {
  declare module.exports: any;
}

declare module 'noble/examples/enter-exit' {
  declare module.exports: any;
}

declare module 'noble/examples/peripheral-explorer' {
  declare module.exports: any;
}

declare module 'noble/examples/pizza/central' {
  declare module.exports: any;
}

declare module 'noble/examples/pizza/pizza' {
  declare module.exports: any;
}

declare module 'noble/lib/characteristic' {
  declare module.exports: any;
}

declare module 'noble/lib/descriptor' {
  declare module.exports: any;
}

declare module 'noble/lib/distributed/bindings' {
  declare module.exports: any;
}

declare module 'noble/lib/hci-socket/acl-stream' {
  declare module.exports: any;
}

declare module 'noble/lib/hci-socket/bindings' {
  declare module.exports: any;
}

declare module 'noble/lib/hci-socket/crypto' {
  declare module.exports: any;
}

declare module 'noble/lib/hci-socket/gap' {
  declare module.exports: any;
}

declare module 'noble/lib/hci-socket/gatt' {
  declare module.exports: any;
}

declare module 'noble/lib/hci-socket/hci' {
  declare module.exports: any;
}

declare module 'noble/lib/hci-socket/signaling' {
  declare module.exports: any;
}

declare module 'noble/lib/hci-socket/smp' {
  declare module.exports: any;
}

declare module 'noble/lib/mac/bindings' {
  declare module.exports: any;
}

declare module 'noble/lib/mac/legacy' {
  declare module.exports: any;
}

declare module 'noble/lib/mac/local-address' {
  declare module.exports: any;
}

declare module 'noble/lib/mac/mavericks' {
  declare module.exports: any;
}

declare module 'noble/lib/mac/uuid-to-address' {
  declare module.exports: any;
}

declare module 'noble/lib/mac/yosemite' {
  declare module.exports: any;
}

declare module 'noble/lib/noble' {
  declare module.exports: any;
}

declare module 'noble/lib/peripheral' {
  declare module.exports: any;
}

declare module 'noble/lib/resolve-bindings-web' {
  declare module.exports: any;
}

declare module 'noble/lib/resolve-bindings' {
  declare module.exports: any;
}

declare module 'noble/lib/service' {
  declare module.exports: any;
}

declare module 'noble/lib/webbluetooth/bindings' {
  declare module.exports: any;
}

declare module 'noble/lib/websocket/bindings' {
  declare module.exports: any;
}

declare module 'noble/test' {
  declare module.exports: any;
}

declare module 'noble/test/test-characteristic' {
  declare module.exports: any;
}

declare module 'noble/test/test-descriptor' {
  declare module.exports: any;
}

declare module 'noble/test/test-peripheral' {
  declare module.exports: any;
}

declare module 'noble/test/test-service' {
  declare module.exports: any;
}

declare module 'noble/with-bindings' {
  declare module.exports: any;
}

declare module 'noble/ws-slave' {
  declare module.exports: any;
}

// Filename aliases
declare module 'noble/examples/advertisement-discovery.js' {
  declare module.exports: $Exports<'noble/examples/advertisement-discovery'>;
}
declare module 'noble/examples/enter-exit.js' {
  declare module.exports: $Exports<'noble/examples/enter-exit'>;
}
declare module 'noble/examples/peripheral-explorer.js' {
  declare module.exports: $Exports<'noble/examples/peripheral-explorer'>;
}
declare module 'noble/examples/pizza/central.js' {
  declare module.exports: $Exports<'noble/examples/pizza/central'>;
}
declare module 'noble/examples/pizza/pizza.js' {
  declare module.exports: $Exports<'noble/examples/pizza/pizza'>;
}
declare module 'noble/index' {
  declare module.exports: $Exports<'noble'>;
}
declare module 'noble/index.js' {
  declare module.exports: $Exports<'noble'>;
}
declare module 'noble/lib/characteristic.js' {
  declare module.exports: $Exports<'noble/lib/characteristic'>;
}
declare module 'noble/lib/descriptor.js' {
  declare module.exports: $Exports<'noble/lib/descriptor'>;
}
declare module 'noble/lib/distributed/bindings.js' {
  declare module.exports: $Exports<'noble/lib/distributed/bindings'>;
}
declare module 'noble/lib/hci-socket/acl-stream.js' {
  declare module.exports: $Exports<'noble/lib/hci-socket/acl-stream'>;
}
declare module 'noble/lib/hci-socket/bindings.js' {
  declare module.exports: $Exports<'noble/lib/hci-socket/bindings'>;
}
declare module 'noble/lib/hci-socket/crypto.js' {
  declare module.exports: $Exports<'noble/lib/hci-socket/crypto'>;
}
declare module 'noble/lib/hci-socket/gap.js' {
  declare module.exports: $Exports<'noble/lib/hci-socket/gap'>;
}
declare module 'noble/lib/hci-socket/gatt.js' {
  declare module.exports: $Exports<'noble/lib/hci-socket/gatt'>;
}
declare module 'noble/lib/hci-socket/hci.js' {
  declare module.exports: $Exports<'noble/lib/hci-socket/hci'>;
}
declare module 'noble/lib/hci-socket/signaling.js' {
  declare module.exports: $Exports<'noble/lib/hci-socket/signaling'>;
}
declare module 'noble/lib/hci-socket/smp.js' {
  declare module.exports: $Exports<'noble/lib/hci-socket/smp'>;
}
declare module 'noble/lib/mac/bindings.js' {
  declare module.exports: $Exports<'noble/lib/mac/bindings'>;
}
declare module 'noble/lib/mac/legacy.js' {
  declare module.exports: $Exports<'noble/lib/mac/legacy'>;
}
declare module 'noble/lib/mac/local-address.js' {
  declare module.exports: $Exports<'noble/lib/mac/local-address'>;
}
declare module 'noble/lib/mac/mavericks.js' {
  declare module.exports: $Exports<'noble/lib/mac/mavericks'>;
}
declare module 'noble/lib/mac/uuid-to-address.js' {
  declare module.exports: $Exports<'noble/lib/mac/uuid-to-address'>;
}
declare module 'noble/lib/mac/yosemite.js' {
  declare module.exports: $Exports<'noble/lib/mac/yosemite'>;
}
declare module 'noble/lib/noble.js' {
  declare module.exports: $Exports<'noble/lib/noble'>;
}
declare module 'noble/lib/peripheral.js' {
  declare module.exports: $Exports<'noble/lib/peripheral'>;
}
declare module 'noble/lib/resolve-bindings-web.js' {
  declare module.exports: $Exports<'noble/lib/resolve-bindings-web'>;
}
declare module 'noble/lib/resolve-bindings.js' {
  declare module.exports: $Exports<'noble/lib/resolve-bindings'>;
}
declare module 'noble/lib/service.js' {
  declare module.exports: $Exports<'noble/lib/service'>;
}
declare module 'noble/lib/webbluetooth/bindings.js' {
  declare module.exports: $Exports<'noble/lib/webbluetooth/bindings'>;
}
declare module 'noble/lib/websocket/bindings.js' {
  declare module.exports: $Exports<'noble/lib/websocket/bindings'>;
}
declare module 'noble/test.js' {
  declare module.exports: $Exports<'noble/test'>;
}
declare module 'noble/test/test-characteristic.js' {
  declare module.exports: $Exports<'noble/test/test-characteristic'>;
}
declare module 'noble/test/test-descriptor.js' {
  declare module.exports: $Exports<'noble/test/test-descriptor'>;
}
declare module 'noble/test/test-peripheral.js' {
  declare module.exports: $Exports<'noble/test/test-peripheral'>;
}
declare module 'noble/test/test-service.js' {
  declare module.exports: $Exports<'noble/test/test-service'>;
}
declare module 'noble/with-bindings.js' {
  declare module.exports: $Exports<'noble/with-bindings'>;
}
declare module 'noble/ws-slave.js' {
  declare module.exports: $Exports<'noble/ws-slave'>;
}
