// flow-typed signature: 8603923980ec14db6dfce845697115ab
// flow-typed version: <<STUB>>/node-hue-api_v^2.4.2/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-hue-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-hue-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-hue-api/hue-api/bridge-discovery' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/commands/configuration-api' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/commands/discovery' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/commands/groups-api' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/commands/info-api' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/commands/lights-api' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/commands/scenes-api' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/commands/schedules-api' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/commands/sensors-api' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/commands/traits/tApiMethod' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/commands/traits/tBodyArguments' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/commands/traits/tDescription' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/commands/traits/tErrorHandling' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/commands/traits/tLightStateBody' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/commands/traits/tPostProcessing' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/commands/traits/tScheduleBody' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/errors' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/httpPromise' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/index' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/lightstate' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/rgb' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/scene' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/scheduledEvent' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/search' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/timer' {
  declare module.exports: any;
}

declare module 'node-hue-api/hue-api/utils' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/bridge-connect' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/getConfiguration-test' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/getLightState-tests' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/groups-test' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/lights-test' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/lightstate-tests' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/locateBridge-tests' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/newLights-test' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/registeredUsers-test' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/registration-tests' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/rgb-tests' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/scene-object-test' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/scene-tests' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/schedule-tests' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/scheduledEvent-tests' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/searchForLights-test' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/sensor-tests' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/setLightName-tests' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/setLightState-tests' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/support/testValues' {
  declare module.exports: any;
}

declare module 'node-hue-api/test/timer-tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-hue-api/hue-api/bridge-discovery.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/bridge-discovery'>;
}
declare module 'node-hue-api/hue-api/commands/configuration-api.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/commands/configuration-api'>;
}
declare module 'node-hue-api/hue-api/commands/discovery.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/commands/discovery'>;
}
declare module 'node-hue-api/hue-api/commands/groups-api.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/commands/groups-api'>;
}
declare module 'node-hue-api/hue-api/commands/info-api.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/commands/info-api'>;
}
declare module 'node-hue-api/hue-api/commands/lights-api.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/commands/lights-api'>;
}
declare module 'node-hue-api/hue-api/commands/scenes-api.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/commands/scenes-api'>;
}
declare module 'node-hue-api/hue-api/commands/schedules-api.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/commands/schedules-api'>;
}
declare module 'node-hue-api/hue-api/commands/sensors-api.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/commands/sensors-api'>;
}
declare module 'node-hue-api/hue-api/commands/traits/tApiMethod.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/commands/traits/tApiMethod'>;
}
declare module 'node-hue-api/hue-api/commands/traits/tBodyArguments.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/commands/traits/tBodyArguments'>;
}
declare module 'node-hue-api/hue-api/commands/traits/tDescription.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/commands/traits/tDescription'>;
}
declare module 'node-hue-api/hue-api/commands/traits/tErrorHandling.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/commands/traits/tErrorHandling'>;
}
declare module 'node-hue-api/hue-api/commands/traits/tLightStateBody.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/commands/traits/tLightStateBody'>;
}
declare module 'node-hue-api/hue-api/commands/traits/tPostProcessing.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/commands/traits/tPostProcessing'>;
}
declare module 'node-hue-api/hue-api/commands/traits/tScheduleBody.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/commands/traits/tScheduleBody'>;
}
declare module 'node-hue-api/hue-api/errors.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/errors'>;
}
declare module 'node-hue-api/hue-api/httpPromise.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/httpPromise'>;
}
declare module 'node-hue-api/hue-api/index.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/index'>;
}
declare module 'node-hue-api/hue-api/lightstate.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/lightstate'>;
}
declare module 'node-hue-api/hue-api/rgb.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/rgb'>;
}
declare module 'node-hue-api/hue-api/scene.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/scene'>;
}
declare module 'node-hue-api/hue-api/scheduledEvent.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/scheduledEvent'>;
}
declare module 'node-hue-api/hue-api/search.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/search'>;
}
declare module 'node-hue-api/hue-api/timer.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/timer'>;
}
declare module 'node-hue-api/hue-api/utils.js' {
  declare module.exports: $Exports<'node-hue-api/hue-api/utils'>;
}
declare module 'node-hue-api/index' {
  declare module.exports: $Exports<'node-hue-api'>;
}
declare module 'node-hue-api/index.js' {
  declare module.exports: $Exports<'node-hue-api'>;
}
declare module 'node-hue-api/test/bridge-connect.js' {
  declare module.exports: $Exports<'node-hue-api/test/bridge-connect'>;
}
declare module 'node-hue-api/test/getConfiguration-test.js' {
  declare module.exports: $Exports<'node-hue-api/test/getConfiguration-test'>;
}
declare module 'node-hue-api/test/getLightState-tests.js' {
  declare module.exports: $Exports<'node-hue-api/test/getLightState-tests'>;
}
declare module 'node-hue-api/test/groups-test.js' {
  declare module.exports: $Exports<'node-hue-api/test/groups-test'>;
}
declare module 'node-hue-api/test/lights-test.js' {
  declare module.exports: $Exports<'node-hue-api/test/lights-test'>;
}
declare module 'node-hue-api/test/lightstate-tests.js' {
  declare module.exports: $Exports<'node-hue-api/test/lightstate-tests'>;
}
declare module 'node-hue-api/test/locateBridge-tests.js' {
  declare module.exports: $Exports<'node-hue-api/test/locateBridge-tests'>;
}
declare module 'node-hue-api/test/newLights-test.js' {
  declare module.exports: $Exports<'node-hue-api/test/newLights-test'>;
}
declare module 'node-hue-api/test/registeredUsers-test.js' {
  declare module.exports: $Exports<'node-hue-api/test/registeredUsers-test'>;
}
declare module 'node-hue-api/test/registration-tests.js' {
  declare module.exports: $Exports<'node-hue-api/test/registration-tests'>;
}
declare module 'node-hue-api/test/rgb-tests.js' {
  declare module.exports: $Exports<'node-hue-api/test/rgb-tests'>;
}
declare module 'node-hue-api/test/scene-object-test.js' {
  declare module.exports: $Exports<'node-hue-api/test/scene-object-test'>;
}
declare module 'node-hue-api/test/scene-tests.js' {
  declare module.exports: $Exports<'node-hue-api/test/scene-tests'>;
}
declare module 'node-hue-api/test/schedule-tests.js' {
  declare module.exports: $Exports<'node-hue-api/test/schedule-tests'>;
}
declare module 'node-hue-api/test/scheduledEvent-tests.js' {
  declare module.exports: $Exports<'node-hue-api/test/scheduledEvent-tests'>;
}
declare module 'node-hue-api/test/searchForLights-test.js' {
  declare module.exports: $Exports<'node-hue-api/test/searchForLights-test'>;
}
declare module 'node-hue-api/test/sensor-tests.js' {
  declare module.exports: $Exports<'node-hue-api/test/sensor-tests'>;
}
declare module 'node-hue-api/test/setLightName-tests.js' {
  declare module.exports: $Exports<'node-hue-api/test/setLightName-tests'>;
}
declare module 'node-hue-api/test/setLightState-tests.js' {
  declare module.exports: $Exports<'node-hue-api/test/setLightState-tests'>;
}
declare module 'node-hue-api/test/support/testValues.js' {
  declare module.exports: $Exports<'node-hue-api/test/support/testValues'>;
}
declare module 'node-hue-api/test/timer-tests.js' {
  declare module.exports: $Exports<'node-hue-api/test/timer-tests'>;
}
