// flow-typed signature: 7ecdf29e0b1d1fa62080c96d26628ad6
// flow-typed version: <<STUB>>/openzwave-shared_v^1.3.4/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'openzwave-shared'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'openzwave-shared' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'openzwave-shared/lib/install-ozw' {
  declare module.exports: any;
}

declare module 'openzwave-shared/lib/openzwave-shared' {
  declare module.exports: any;
}

declare module 'openzwave-shared/lib/ozwpaths' {
  declare module.exports: any;
}

declare module 'openzwave-shared/test' {
  declare module.exports: any;
}

declare module 'openzwave-shared/test2' {
  declare module.exports: any;
}

declare module 'openzwave-shared/test3' {
  declare module.exports: any;
}

// Filename aliases
declare module 'openzwave-shared/lib/install-ozw.js' {
  declare module.exports: $Exports<'openzwave-shared/lib/install-ozw'>;
}
declare module 'openzwave-shared/lib/openzwave-shared.js' {
  declare module.exports: $Exports<'openzwave-shared/lib/openzwave-shared'>;
}
declare module 'openzwave-shared/lib/ozwpaths.js' {
  declare module.exports: $Exports<'openzwave-shared/lib/ozwpaths'>;
}
declare module 'openzwave-shared/test.js' {
  declare module.exports: $Exports<'openzwave-shared/test'>;
}
declare module 'openzwave-shared/test2.js' {
  declare module.exports: $Exports<'openzwave-shared/test2'>;
}
declare module 'openzwave-shared/test3.js' {
  declare module.exports: $Exports<'openzwave-shared/test3'>;
}
