// flow-typed signature: c87ae520d6872c8c48a4b1cba80db633
// flow-typed version: <<STUB>>/yahoo-weather_v^2.2.2/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yahoo-weather'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'yahoo-weather' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yahoo-weather/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yahoo-weather/dist/index.js' {
  declare module.exports: $Exports<'yahoo-weather/dist/index'>;
}
declare module 'yahoo-weather/index' {
  declare module.exports: $Exports<'yahoo-weather'>;
}
declare module 'yahoo-weather/index.js' {
  declare module.exports: $Exports<'yahoo-weather'>;
}
